### ISSUE TITLE
Nested blocks show additional border

### ISSUE THREAD

**Issue by leevigraham** [spicywebau/craft-neo#556]
#### Description

Additional border `:before` element appears on nested blocks. This can be resolved with

```css
.ni_block_children::before {
  display: none;
}
```

![image](https://user-images.githubusercontent.com/25124/162955256-586d704c-94fa-468c-8ba2-1f04119b2c17.png)
![image](https://user-images.githubusercontent.com/25124/162955633-4f3aa92a-eb33-463e-86eb-ca9fa6d69d8b.png)

#### Other information
- Neo version: 2.13.3
- Craft version: Craft CMS 3.7.38
