### ISSUE TITLE
Craft 4: Saving entry will cause PDOException: Integrity constraint violation

### ISSUE THREAD

**Issue by elfacht** [spicywebau/craft-neo#571]
#### Description

Saving an entry with a pretty simple Neo field will cause a PDOException:

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`pcom22`.`pcom_neoblocks_owners`, CONSTRAINT `pcom_fk_ienyuwcdxyjkdparmjxwlxkpxwenmslsmymu` FOREIGN KEY (`blockId`) REFERENCES `pcom_neoblocks` (`id`) ON DELETE CASCADE) in /app/cms/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /app/cms/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /app/cms/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute(NULL)
#2 /app/cms/vendor/craftcms/cms/src/helpers/Db.php(968): yii\db\Command->execute()
#3 /app/cms/vendor/spicyweb/craft-neo/src/services/Fields.php(584): craft\helpers\Db::batchInsert('{{%neoblocks_ow...', Array, Array)
#4 /app/cms/vendor/spicyweb/craft-neo/src/Field.php(773): benf\neo\services\Fields->createRevisionBlocks(Object(benf\neo\Field), Object(craft\elements\Entry), Object(craft\elements\Entry))
#5 /app/cms/vendor/craftcms/cms/src/base/Element.php(4530): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), true)
#6 /app/cms/vendor/craftcms/cms/src/elements/Entry.php(2009): craft\base\Element->afterPropagate(true)
#7 /app/cms/vendor/craftcms/cms/src/services/Elements.php(1343): craft\elements\Entry->afterPropagate(true)
#8 /app/cms/vendor/craftcms/cms/src/services/Revisions.php(160): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#9 /app/cms/vendor/craftcms/cms/src/elements/Entry.php(2013): craft\services\Revisions->createRevision(Object(craft\elements\Entry), 1, '')
#10 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2734): craft\elements\Entry->afterPropagate(false)
#11 /app/cms/vendor/craftcms/cms/src/services/Elements.php(789): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#12 /app/cms/vendor/craftcms/cms/src/controllers/ElementsController.php(871): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#13 [internal function]: craft\controllers\ElementsController->actionSave()
#14 /app/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /app/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /app/cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save', Array)
#17 /app/cms/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/save', Array)
#18 /app/cms/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/save', Array)
#19 /app/cms/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /app/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /app/cms/web/index.php(21): yii\base\Application->run()
#22 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`pcom22`.`pcom_neoblocks_owners`, CONSTRAINT `pcom_fk_ienyuwcdxyjkdparmjxwlxkpxwenmslsmymu` FOREIGN KEY (`blockId`) REFERENCES `pcom_neoblocks` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `pcom_neoblocks_owners` (`blockId`, `ownerId`, `sortOrder`) VALUES (584, 618, 1), (542, 618, 2), (577, 618, 3), (578, 618, 4), (579, 618, 5), (544, 618, 6) in /app/cms/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /app/cms/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `pc...')
#1 /app/cms/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `pc...')
#2 /app/cms/vendor/craftcms/cms/src/helpers/Db.php(968): yii\db\Command->execute()
#3 /app/cms/vendor/spicyweb/craft-neo/src/services/Fields.php(584): craft\helpers\Db::batchInsert('{{%neoblocks_ow...', Array, Array)
#4 /app/cms/vendor/spicyweb/craft-neo/src/Field.php(773): benf\neo\services\Fields->createRevisionBlocks(Object(benf\neo\Field), Object(craft\elements\Entry), Object(craft\elements\Entry))
#5 /app/cms/vendor/craftcms/cms/src/base/Element.php(4530): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), true)
#6 /app/cms/vendor/craftcms/cms/src/elements/Entry.php(2009): craft\base\Element->afterPropagate(true)
#7 /app/cms/vendor/craftcms/cms/src/services/Elements.php(1343): craft\elements\Entry->afterPropagate(true)
#8 /app/cms/vendor/craftcms/cms/src/services/Revisions.php(160): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#9 /app/cms/vendor/craftcms/cms/src/elements/Entry.php(2013): craft\services\Revisions->createRevision(Object(craft\elements\Entry), 1, '')
#10 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2734): craft\elements\Entry->afterPropagate(false)
#11 /app/cms/vendor/craftcms/cms/src/services/Elements.php(789): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#12 /app/cms/vendor/craftcms/cms/src/controllers/ElementsController.php(871): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#13 [internal function]: craft\controllers\ElementsController->actionSave()
#14 /app/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /app/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /app/cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save', Array)
#17 /app/cms/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/save', Array)
#18 /app/cms/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/save', Array)
#19 /app/cms/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /app/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /app/cms/web/index.php(21): yii\base\Application->run()
#22 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1452
    [2] => Cannot add or update a child row: a foreign key constraint fails (`pcom22`.`pcom_neoblocks_owners`, CONSTRAINT `pcom_fk_ienyuwcdxyjkdparmjxwlxkpxwenmslsmymu` FOREIGN KEY (`blockId`) REFERENCES `pcom_neoblocks` (`id`) ON DELETE CASCADE)
)
```
This happens since the update to Craft 4. The Neo field has two child blocks containing assets and text fields:

```yml
childBlocks:
  - mediaboxImage
  - footnote
field: 13953d81-6ba1-43ab-bdc5-ca496efd7535 # Blocks
fieldLayouts:
  a071de16-1feb-463c-b765-a2a0b0be3ed2:
    tabs:
      -
        elements:
          -
            fieldUid: 91f56b97-8b36-4c72-af13-5aaf2687bafe # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf9d4adc-5e27-40ba-b0b1-28a113344b4c
            warning: null
            width: 100
          -
            fieldUid: 3d1b9b41-5e8e-448f-a6fc-245351f28e6f # Textbox
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c51fa347-baff-41ac-9813-3a41efcac596
            warning: null
            width: 100
        name: Content
        uid: ffb85b0e-de16-4c0c-9f57-c13d638be281
group: null
handle: mediabox
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Mediabox
sortOrder: 1
topLevel: true
```

The setup is pretty fresh and new, so no wild things are going on.  
**The entry will be saved though (sometimes), but you have to deal with the internal server error message first!**

#### Steps to reproduce
1. Create a Neo field in Craft 3.7.40.1 with simple text block and field
2. Create child blocks with simple asset fields, maybe a text field
3. Update to Craft 4
4. Save entry with Neo field
5. First save may work, after that: it won't

![Screenshot 2022-05-05 um 21 14 27](https://user-images.githubusercontent.com/529443/167009078-d0933e5a-6383-432c-b625-422b93b63b5b.jpg)
![Screenshot 2022-05-05 um 21 14 31](https://user-images.githubusercontent.com/529443/167009091-8987a267-2b84-4838-8f43-cc142fa08b66.jpg)
![Screenshot 2022-05-05 um 21 14 35](https://user-images.githubusercontent.com/529443/167009096-49d6de4f-6d0d-49e8-bd4f-2e70def0232d.jpg)
![Screenshot 2022-05-05 um 21 14 39](https://user-images.githubusercontent.com/529443/167009101-3597a5b8-e40a-4e38-a081-427fb859d1a3.jpg)

#### Other information
- Neo version: 3.0.1
- Craft version: 4.0.0.1
- Is eager-loading used? No
