### ISSUE TITLE
yaml config doesn't match with minimal required fields for blocktypes

### ISSUE THREAD

**Issue by sfsmfc** [spicywebau/craft-neo#687]
#### Description
If I store a new neo blocktype, I get for example the following content in yaml file:

```
childBlocks: '*'
description: ''
enabled: true
field: 15db6f2c-b9a0-4446-bfd8-994c1348c91f # Content Builder
fieldLayouts:
  4cbee43f-3896-4ae4-a19a-8fd1d3bf80da:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            style: tip
            tip: ''
            type: craft\fieldlayoutelements\Tip
            uid: 114aa129-bb0f-4c1b-86fb-cd3fdfddf298
            userCondition: null
        name: Content
        uid: 92fa00a9-67d4-4551-97ed-668a328ea567
        userCondition: null
group: null
handle: neuerBlocktype
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'neuer Blocktype'
sortOrder: 2
topLevel: true
```

If you compare this fields with the required fields under vendor/spicyweb/craft-neo/src/Field.php:321ff, you will missing something like "ignorePermissions" or "conditions". With direct access to the array values, we get problems, if these values are not present. We should protect this direct access with an "isset" request before. 

#### Steps to reproduce
1. Create a new blocktype.
2. Open the config file for this new blocktype.
3. Compare the output with vendor/spicyweb/craft-neo/src/Field.php:321ff.
4. Try to export and import your neo field with an import/export plugin like field-manager or architect. The import will failed because of missing required attributes.

#### Other information
- Neo version: 3.4.1
- Craft version: 4.3.1
